---
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/restapi
    username: restapi
    password: restapi
  liquibase:
    contexts: dev
logging:
  level:
    web: debug
    sql: debug
    sample.pokedex.restapi: debug

